"""Interactive kickstart file generator.

Port of ``kickstart/prepare-ks.sh``. Run with::

    python3 -m fedora_setup.kickstart.prepare_ks
"""

from __future__ import annotations

import argparse
import datetime as _dt
import getpass
import shutil
import subprocess
import sys
from pathlib import Path

from .. import colors

KICKSTART_DIR = Path(__file__).resolve().parent.parent.parent / "kickstart"
DEFAULT_OUTPUT = KICKSTART_DIR / "fedora-dev.ks"

DISK_LAYOUTS: tuple[tuple[str, str], ...] = (
    ("automatic (LVM)", "automatic"),
    ("manual (Anaconda prompts you)", "manual"),
    ("automatic (Btrfs)", "btrfs"),
)

TIMEZONE_CHOICES = (
    "America/New_York",
    "America/Los_Angeles",
    "Europe/London",
    "Asia/Kolkata",
    "Asia/Tokyo",
    "UTC",
)

DEFAULT_SCRIPT_URL = (
    "https://raw.githubusercontent.com/mahsoommoosa42/fedora-setup/main/setup.sh"
)


def _prompt(prompt_text: str, default: str | None = None) -> str:
    label = f"{prompt_text} [{default}]: " if default else f"{prompt_text}: "
    try:
        value = input(label).strip()
    except EOFError:
        value = ""
    if not value and default is not None:
        return default
    return value


def _prompt_password(prompt_text: str) -> str:
    while True:
        password1 = getpass.getpass(f"{prompt_text}: ")
        password2 = getpass.getpass("Confirm password: ")
        if password1 != password2:
            colors.warn("Passwords do not match")
            continue
        if len(password1) < 8:
            colors.warn("Password must be at least 8 characters")
            continue
        return password1


def _prompt_choice(prompt_text: str, options: tuple[str, ...]) -> int:
    print()
    print(prompt_text)
    for idx, option in enumerate(options, start=1):
        print(f"  {idx}) {option}")
    print()
    while True:
        raw = _prompt(f"Selection [1-{len(options)}]")
        if raw.isdigit() and 1 <= int(raw) <= len(options):
            return int(raw) - 1
        colors.warn("Invalid selection")


def _hash_password(password: str) -> str:
    """Hash a password using SHA-512 crypt.

    Tries the stdlib ``crypt`` module first (Python <3.13), then ``openssl
    passwd -6``, then ``mkpasswd`` from the ``whois`` package as a final
    fallback. Aborts the program if none of these are available.
    """
    try:  # pragma: no cover — depends on Python build
        import crypt as _crypt

        return _crypt.crypt(password, _crypt.mksalt(_crypt.METHOD_SHA512))
    except (ImportError, AttributeError):
        pass

    if shutil.which("openssl"):
        result = subprocess.run(
            ["openssl", "passwd", "-6", password],
            capture_output=True,
            text=True,
            check=False,
        )
        if result.returncode == 0 and result.stdout.strip():
            return result.stdout.strip()

    if shutil.which("mkpasswd"):
        result = subprocess.run(
            ["mkpasswd", "-m", "sha-512", password],
            capture_output=True,
            text=True,
            check=False,
        )
        if result.returncode == 0 and result.stdout.strip():
            return result.stdout.strip()

    colors.die(
        "Cannot hash password: neither openssl nor mkpasswd is available, "
        "and the stdlib crypt module is missing. Install one of them and retry."
    )
    return ""  # pragma: no cover — die() exits


def _disk_block(layout_key: str) -> str:
    if layout_key == "automatic":
        return (
            "# Automatic partitioning\n"
            "clearpart --all --initlabel\n"
            "autopart --type=lvm\n"
        )
    if layout_key == "btrfs":
        return (
            "# Automatic Btrfs partitioning\n"
            "clearpart --all --initlabel\n"
            "autopart --type=btrfs\n"
        )
    return "# Manual partitioning — Anaconda will pause and let you configure disks\n"


def _generate_ks(
    *,
    username: str,
    full_name: str,
    hashed_pw: str,
    hostname: str,
    timezone: str,
    disk_layout_label: str,
    disk_layout_key: str,
    script_url: str,
) -> str:
    timestamp = _dt.datetime.now().astimezone().isoformat(timespec="seconds")
    head = f"""\
# =============================================================================
# fedora-dev.ks — Generated by prepare_ks.py
# =============================================================================
# Username: {username}
# Full name: {full_name}
# Hostname: {hostname}
# Timezone: {timezone}
# Disk layout: {disk_layout_label}
# Generated: {timestamp}
# =============================================================================

# ── Installation source & method ─────────────────────────────────────────────
graphical
url --mirrorlist=https://mirrors.fedoraproject.org/mirrorlist?repo=fedora-$releasever&arch=$basearch

# ── Localization ──────────────────────────────────────────────────────────────
lang en_US.UTF-8
keyboard --vckeymap=us --xlayouts=us
timezone {timezone} --utc

# ── Network ───────────────────────────────────────────────────────────────────
network --bootproto=dhcp --device=link --activate --onboot=on
network --hostname={hostname}

# ── Security ──────────────────────────────────────────────────────────────────
rootpw --lock
user --name={username} \\
     --groups=wheel \\
     --password={hashed_pw} \\
     --iscrypted \\
     --gecos="{full_name}"

selinux --enforcing
firewall --enabled --service=ssh

# ── Bootloader & Disk Layout ───────────────────────────────────────────────────
bootloader --append="crashkernel=auto" --location=mbr --timeout=5

"""

    packages = """\

# ── Package selection ─────────────────────────────────────────────────────────
%packages
@kde-desktop-environment
@development-tools
@rpm-development-tools
curl
wget
git
bash-completion
-exclude weakdeps
# Remove some bloat
-plasma-discover
-kdeconnectd
-akregator
-kmail
-konqueror
%end

"""

    post = f"""\
# ── Post-install: run dev setup script ───────────────────────────────────────
%post --log=/var/log/ks-post.log
set -euo pipefail

# Download and run the setup script
SCRIPT_URL="{script_url}"
SCRIPT_LOCAL="/home/{username}/setup.sh"

echo "Downloading setup script from $SCRIPT_URL..."
curl -fsSL "$SCRIPT_URL" -o "$SCRIPT_LOCAL"
chmod +x "$SCRIPT_LOCAL"

echo "Running setup script as {username}..."
sudo -u {username} bash "$SCRIPT_LOCAL"

echo "Post-install complete." >> /var/log/ks-post.log
%end

# ── Reboot after install ──────────────────────────────────────────────────────
reboot
"""

    return head + _disk_block(disk_layout_key) + packages + post


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help=f"Path to write the generated kickstart file (default: {DEFAULT_OUTPUT})",
    )
    args = parser.parse_args(argv)

    print(colors.BOLD)
    print("  Fedora Kickstart Configuration Wizard")
    print("  ======================================")
    print(colors.RESET)
    print()

    username = _prompt("Username", "moosa")
    full_name = _prompt("Full name (gecos)", "Moosa Mahsoom")
    password = _prompt_password("Password")
    hostname = _prompt("Hostname", "fedora-dev")

    tz_idx = _prompt_choice("Select timezone", TIMEZONE_CHOICES)
    timezone = TIMEZONE_CHOICES[tz_idx]

    disk_idx = _prompt_choice(
        "Select disk layout",
        tuple(label for label, _ in DISK_LAYOUTS),
    )
    disk_layout_label, disk_layout_key = DISK_LAYOUTS[disk_idx]

    script_url = _prompt("Setup script URL", DEFAULT_SCRIPT_URL)

    hashed_pw = _hash_password(password)

    print()
    print(f"{colors.BOLD}Configuration Summary:{colors.RESET}")
    print(f"  Username   : {username}")
    print(f"  Full name  : {full_name}")
    print(f"  Hostname   : {hostname}")
    print(f"  Timezone   : {timezone}")
    print(f"  Disk layout: {disk_layout_label}")
    print(f"  Script URL : {script_url}")
    print()

    confirm = _prompt("Generate kickstart file? [Y/n]", "y").lower()
    if confirm == "n":
        colors.info("Aborted")
        return 0

    output = args.output
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(
        _generate_ks(
            username=username,
            full_name=full_name,
            hashed_pw=hashed_pw,
            hostname=hostname,
            timezone=timezone,
            disk_layout_label=disk_layout_label,
            disk_layout_key=disk_layout_key,
            script_url=script_url,
        ),
        encoding="utf-8",
    )

    colors.success(f"Kickstart file generated: {output}")
    colors.info("")
    colors.info("Next steps:")
    colors.info("  1. Download Fedora ISO: python3 -m fedora_setup.kickstart.download_iso")
    colors.info("  2. Bake kickstart into ISO:")
    colors.info(f"     mkksiso --ks {output} <original.iso> <custom.iso>")
    colors.info("  3. Write to USB and boot")
    return 0


if __name__ == "__main__":
    sys.exit(main())
