#!/usr/bin/env bash
# =============================================================================
# prepare-ks.sh — Interactive kickstart file generator
# Prompts for all required settings and generates a ready-to-use fedora-dev.ks
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/../lib/colors.sh"

OUTPUT_FILE="$SCRIPT_DIR/fedora-dev.ks"  # Generated file (contains password hash)

# ── Prompts ───────────────────────────────────────────────────────────────────

prompt() {
    local var_name="$1" prompt_text="$2" default="${3:-}"
    local value

    if [[ -n "$default" ]]; then
        read -rp "$prompt_text [$default]: " value
        value="${value:-$default}"
    else
        read -rp "$prompt_text: " value
    fi

    # Export to caller's scope
    printf -v "$var_name" '%s' "$value"
}

prompt_password() {
    local var_name="$1" prompt_text="$2"
    local password1 password2

    while true; do
        read -s -rp "$prompt_text: " password1
        echo
        read -s -rp "Confirm password: " password2
        echo

        if [[ "$password1" == "$password2" ]]; then
            if [[ ${#password1} -ge 8 ]]; then
                printf -v "$var_name" '%s' "$password1"
                break
            else
                warn "Password must be at least 8 characters"
            fi
        else
            warn "Passwords do not match"
        fi
    done
}

prompt_choice() {
    local var_name="$1" prompt_text="$2"; shift 2
    local options=("$@")
    local choice

    echo ""
    echo "$prompt_text"
    for i in "${!options[@]}"; do
        echo "  $((i+1))) ${options[$i]}"
    done
    echo ""

    while true; do
        read -rp "Selection [1-${#options[@]}]: " choice
        if [[ "$choice" =~ ^[1-9]$ ]] && [[ "$choice" -le ${#options[@]} ]]; then
            printf -v "$var_name" '%s' "${options[$((choice-1))]}"
            break
        fi
        warn "Invalid selection"
    done
}

# ── Hash password ─────────────────────────────────────────────────────────────

hash_password() {
    local password="$1"

    # Try python3 with crypt module first
    if command -v python3 &>/dev/null; then
        if python3 -c "import crypt" 2>/dev/null; then
            python3 -c "import crypt; print(crypt.crypt('$password', crypt.mksalt(crypt.METHOD_SHA512)))"
            return
        fi
    fi

    # Try openssl
    if command -v openssl &>/dev/null; then
        openssl passwd -6 "$password"
        return
    fi

    # Fallback: use a simple SHA-256 hash (kickstart will accept it, though not ideal)
    die "Cannot hash password: neither python3 with crypt module nor openssl is available. Please install one."
}

# ── Generate kickstart file ───────────────────────────────────────────────────

generate_ks() {
    local username="$1" hashed_pw="$2" full_name="$3"
    local disk_layout="$4" timezone="$5" hostname="$6"
    local script_url="$7"

    cat <<EOF
# =============================================================================
# fedora-dev.ks — Generated by prepare-ks.sh
# =============================================================================
# Username: $username
# Full name: $full_name
# Hostname: $hostname
# Timezone: $timezone
# Disk layout: $disk_layout
# Generated: $(date -Iseconds)
# =============================================================================

# ── Installation source & method ─────────────────────────────────────────────
graphical
url --mirrorlist=https://mirrors.fedoraproject.org/mirrorlist?repo=fedora-\$releasever&arch=\$basearch

# ── Localization ──────────────────────────────────────────────────────────────
lang en_US.UTF-8
keyboard --vckeymap=us --xlayouts=us
timezone $timezone --utc

# ── Network ───────────────────────────────────────────────────────────────────
network --bootproto=dhcp --device=link --activate --onboot=on
network --hostname=$hostname

# ── Security ──────────────────────────────────────────────────────────────────
rootpw --lock
user --name=$username \\
     --groups=wheel \\
     --password=$hashed_pw \\
     --iscrypted \\
     --gecos="$full_name"

selinux --enforcing
firewall --enabled --service=ssh

# ── Bootloader & Disk Layout ───────────────────────────────────────────────────
bootloader --append="crashkernel=auto" --location=mbr --timeout=5

EOF

    case "$disk_layout" in
        automatic)
            cat <<EOF
# Automatic partitioning
clearpart --all --initlabel
autopart --type=lvm
EOF
            ;;
        manual)
            cat <<EOF
# Manual partitioning — Anaconda will pause and let you configure disks
EOF
            ;;
        btrfs)
            cat <<EOF
# Automatic Btrfs partitioning
clearpart --all --initlabel
autopart --type=btrfs
EOF
            ;;
    esac

    cat <<EOF

# ── Package selection ─────────────────────────────────────────────────────────
%packages
@kde-desktop-environment
@development-tools
@rpm-development-tools
curl
wget
git
bash-completion
-exclude weakdeps
# Remove some bloat
-plasma-discover
-kdeconnectd
-akregator
-kmail
-konqueror
%end

# ── Post-install: run dev setup script ───────────────────────────────────────
%post --log=/var/log/ks-post.log
set -euo pipefail

# Download and run the setup script
SCRIPT_URL="$script_url"
SCRIPT_LOCAL="/home/$username/setup.sh"

echo "Downloading setup script from \$SCRIPT_URL..."
curl -fsSL "\$SCRIPT_URL" -o "\$SCRIPT_LOCAL"
chmod +x "\$SCRIPT_LOCAL"

echo "Running setup script as $username..."
sudo -u $username bash "\$SCRIPT_LOCAL"

echo "Post-install complete." >> /var/log/ks-post.log
%end

# ── Reboot after install ──────────────────────────────────────────────────────
reboot
EOF
}

# ── Main ───────────────────────────────────────────────────────────────────────

echo -e "${BOLD}"
echo "  Fedora Kickstart Configuration Wizard"
echo "  ======================================"
echo -e "${RESET}"
echo ""

prompt USERNAME "Username" "moosa"
prompt FULL_NAME "Full name (gecos)" "Moosa Mahsoom"
prompt_password PASSWORD "Password"
prompt HOSTNAME "Hostname" "fedora-dev"
prompt_choice TIMEZONE "Select timezone" \
    "America/New_York" \
    "America/Los_Angeles" \
    "Europe/London" \
    "Asia/Kolkata" \
    "Asia/Tokyo" \
    "UTC"

prompt_choice DISK_LAYOUT "Select disk layout" \
    "automatic (LVM)" \
    "manual (Anaconda prompts you)" \
    "automatic (Btrfs)"

# GitHub repo URL for setup.sh
SCRIPT_URL="https://raw.githubusercontent.com/mahsoommoosa42/fedora-setup/main/setup.sh"
read -rp "Setup script URL [$SCRIPT_URL]: " input_url
SCRIPT_URL="${input_url:-$SCRIPT_URL}"

# Hash the password
HASHED_PW="$(hash_password "$PASSWORD")"

echo ""
echo -e "${BOLD}Configuration Summary:${RESET}"
echo "  Username   : $USERNAME"
echo "  Full name  : $FULL_NAME"
echo "  Hostname   : $HOSTNAME"
echo "  Timezone   : $TIMEZONE"
echo "  Disk layout: $DISK_LAYOUT"
echo "  Script URL : $SCRIPT_URL"
echo ""

read -rp "Generate kickstart file? [Y/n]: " confirm
if [[ $REPLY =~ ^[Nn]$ ]]; then
    info "Aborted"
    exit 0
fi

generate_ks "$USERNAME" "$HASHED_PW" "$FULL_NAME" "$DISK_LAYOUT" \
           "$TIMEZONE" "$HOSTNAME" "$SCRIPT_URL" > "$OUTPUT_FILE"

success "Kickstart file generated: $OUTPUT_FILE"
info ""
info "Next steps:"
info "  1. Download Fedora ISO: ./download-iso.sh"
info "  2. Bake kickstart into ISO:"
info "     mkksiso --ks $OUTPUT_FILE <original.iso> <custom.iso>"
info "  3. Write to USB and boot"